version: 2

jobs:
  lint:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
  build:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn build
      - run: yarn build-storybook
      - run: yarn test
      - run: yarn chromatic test --app-code=aa1gc2e7mfl --exit-zero-on-changes
      - run: |
          if [ $CIRCLE_BRANCH = "master" ]
          then
            yarn release
          fi

workflows:
  version: 2
  lint-build:
    jobs:
      - build
